services:
  web:
    build: .
    container_name: php_app
    restart: always
    expose:
      - "80"
    volumes:
      - ./TaskManager:/var/www/html
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_manager
      MYSQL_USER: usuario
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./Dump20260413.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "8081:80"
      - "8443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - web
    networks:
      - app_network

  uptime-kuma:
    image: louislam/uptime-kuma:1
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - uptime_kuma_data:/app/data
    networks:
      - app_network

  dozzle:
    image: amir20/dozzle:latest
    restart: always
    ports:
      - "9999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app_network

networks:
  app_network:

volumes:
  db_data:
  uptime_kuma_data:
